### PR TITLE
feat: rewrite of update vim plugins script

### PR DESCRIPTION
**Pull request by MoritzBoehme**
This is my first, currently incomplete attempt of rewriting the update script in python.
I would be grateful for any feedback, should someone take the time to look through my rough first draft.

### CODE REVIEW

**Comment by jooooscha** [comment]
Wow, thank you. This looks great so far.

For now, I only noticed that your default license would be UNFREE, which I guess is not correct in most cases?
Maybe, the default should be `unspecified`?

Related to this: Nixvim uses nix overrides to correct wrong licenses. I am not sure if this will be a problem with your script. But If so, we should change the syntax of the manifest.txt to include a column for license specification. I think that would be a cleaner way of specifying them manually.

Just for the record: #3

**Comment by MoritzBoehme** [comment]
>Wow, thank you. This looks great so far.

Thanks :) I'll try to continue working on this, but I sadly don't know how much time I can dedicate to this, but I'll try to work on it over the next few weekends.

>For now, I only noticed that your default license would be UNFREE, which I guess is not correct in most cases?
Maybe, the default should be unspecified?

Yes, this would probably not be correct in many cases. Most of the time this will be the case if we couldn't find a license. My reason behind this was that in the cases, where the license is **truly** not available, it is probably an unfree license.
Personally, I do not really mind using unfree plugins, but considering some people are very strict about this, it seems better to accept these hopefully few false positives.

>Related to this: Nixvim uses nix overrides to correct wrong licenses. I am not sure if this will be a problem with your script. But If so, we should change the syntax of the manifest.txt to include a column for license specification. I think that would be a cleaner way of specifying them manually.

I could see this being a good compromise. If there are some repositories, where automatic license detection fails, one could just add it via the spec and this shouldn't be an issue anymore.  The syntax should probably just be something like `source:owner/repo:gitref:rename:license` where `license` is the nix name of the license.

**Comment by jooooscha** [comment]
> Personally, I do not really mind using unfree plugins, but considering some people are very strict about this, it seems better to accept these hopefully few false positives

I think it would, still, be better to state the license to be unknown rather than to claim it's definitely unfree.
Someone cautious about unfree licenses could then check and confirm if the license is actually unfree.

> The syntax should probably just be something like source:owner/repo:gitref:rename:license where license is the nix name of the license.

This is exactly what I was thinking about :)

**Comment by MoritzBoehme** [comment]
> think it would, still, be better to state the license to be unknown rather than to claim it's definitely unfree.

Okay, in this case I think the `unknown` license should just result in leaving the licenses empty, as there is no `unkown` license in nixpkgs. And for unfree licenses the correct way to set them is via the spec.

**Comment by jooooscha** [comment]
Any update on this?

**Comment by MoritzBoehme** [comment]
Sadly not. I currently have a lot to do for work and university, so I couldn't revisit this yet. I'll try to keep it in mind, but I really can't tell when I'll get around to it.

**Comment by jooooscha** [comment]
Could you document the state of the script shortly? I am thinking about a list of things that should work already, things that are still missing, and things we still have to figure out.

This would help me -- and others -- to continue your work.

Thanks

**Comment by jooooscha** [comment]
Closing in favor of #71

**Comment by MoritzBoehme** [comment]
Sorry @jooooscha, for not responding for such a long time. But I'm happy to see you could finish the remaining rewrite on your own. Again, sorry for causing any inconvenience.

**Pull request closed without merging**
